# Streamlit Secrets Template
# Copy this template and add your actual values in Streamlit Cloud secrets

# AI API Keys (Primary: Gemini, Fallback: OpenRouter)
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"
OPENROUTER_API_KEY = "YOUR_OPENROUTER_API_KEY_HERE"

# Vector Database Configuration (Using FAISS for cloud compatibility)
VECTOR_DB_TYPE = "faiss"
VECTOR_DB_PATH = "./vector_store_faiss"
COLLECTION_NAME = "pdf_chunks"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# AI Chatbot Configuration - Conversational & Concise
MAX_CONTEXT_CHUNKS = "2"
MAX_CONTEXT_LENGTH = "2000"
MIN_SIMILARITY_THRESHOLD = "0.65"
ENABLE_CITATIONS = "true"
ENABLE_CONTEXT_EXPANSION = "false"
LLM_MODEL = "mistralai/mistral-7b-instruct:free"
MAX_RESPONSE_TOKENS = "350"
TEMPERATURE = "0.7"

# Text Processing Configuration
MIN_CHUNK_LENGTH = "80"
MAX_CHUNK_LENGTH = "1500"
INCLUDE_METADATA = "true"

# Performance Configuration
ENABLE_PERFORMANCE_LOGGING = "false"
LOG_LEVEL = "WARNING"
SUPPRESS_WARNINGS = "true"
FILTER_PDF_FILES = "true"
SHOW_FILE_SUMMARY = "false"
