# Streamlit Secrets for Production Deployment
# Add your actual API key manually in Streamlit Cloud secrets

OPENROUTER_API_KEY = "YOUR_OPENROUTER_API_KEY_HERE"
AZURE_STORAGE_ACCOUNT_NAME = "edifystorageaccount"
AZURE_STORAGE_CONTAINER_NAME = "edifydocumentcontainer"
AZURE_BLOB_FOLDER_PATH = "edipedia/2025-2026/"
AZURE_STORAGE_CONNECTION_STRING = ""
AZURE_STORAGE_ACCOUNT_KEY = ""

# Vector Database Configuration
VECTOR_DB_TYPE = "chromadb"
VECTOR_DB_PATH = "./vector_store"
COLLECTION_NAME = "pdf_chunks"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# AI Chatbot Configuration
MAX_CONTEXT_CHUNKS = "2"
MAX_CONTEXT_LENGTH = "2000"
MIN_SIMILARITY_THRESHOLD = "0.65"
ENABLE_CITATIONS = "true"
ENABLE_CONTEXT_EXPANSION = "false"
LLM_MODEL = "mistralai/mistral-7b-instruct:free"
MAX_RESPONSE_TOKENS = "350"
TEMPERATURE = "0.7"

# Text Processing
MIN_CHUNK_LENGTH = "80"
MAX_CHUNK_LENGTH = "1500"
INCLUDE_METADATA = "true"

# Performance Monitoring
ENABLE_PERFORMANCE_LOGGING = "false"
LOG_LEVEL = "WARNING"
SUPPRESS_WARNINGS = "true"

# File Processing
FILTER_PDF_FILES = "true"
SHOW_FILE_SUMMARY = "false"
MAX_WORKERS = "2"
CHUNK_SIZE = "800"
CHUNK_OVERLAP = "150"
BATCH_SIZE = "15"
MAX_MEMORY_MB = "1536"

# Enhanced Processing
ENABLE_OCR = "false"
OCR_LANGUAGE = "eng"
OCR_DPI = "250"
IMAGE_TO_TEXT = "false"
ENABLE_REPAIR = "false"
MAX_FILE_SIZE_MB = "75"
SUPPRESS_PDF_WARNINGS = "true"
